services:
  nginx:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: openbiocure-nginx
    ports:
      - "80:80"
    volumes:
      # Mount configs for easy updates without rebuilding
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf.d:/etc/nginx/conf.d:ro
      - ./static:/etc/nginx/static:ro
      - ./assets:/etc/nginx/assets:ro
    restart: unless-stopped
    networks:
      - openbiocure-network

networks:
  openbiocure-network:
    driver: bridge 